In [1]:
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[-1.2169e+23,  4.5786e-41, -2.2868e-02],
        [ 3.0908e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  7.7052e+31,  1.9447e+31],
        [ 5.0207e+28,  2.3329e-18,  4.2330e+21]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.6609, 0.4991, 0.1838],
        [0.9134, 0.5779, 0.1405],
        [0.1481, 0.2524, 0.9927],
        [0.7964, 0.4988, 0.0583],
        [0.6264, 0.3248, 0.6647]])


In [7]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.rand(5,3)
print(x)

tensor([[0.2036, 0.2275, 0.4280],
        [0.1183, 0.4738, 0.9196],
        [0.0397, 0.3150, 0.8544],
        [0.5540, 0.3618, 0.6283],
        [0.3629, 0.9835, 0.1878]])


In [9]:
x[:, 1]

tensor([0.2275, 0.4738, 0.3150, 0.3618, 0.9835])

In [10]:
x.view(15,1)

tensor([[0.2036],
        [0.2275],
        [0.4280],
        [0.1183],
        [0.4738],
        [0.9196],
        [0.0397],
        [0.3150],
        [0.8544],
        [0.5540],
        [0.3618],
        [0.6283],
        [0.3629],
        [0.9835],
        [0.1878]])

In [11]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu', torch.double))

tensor([[1.2036, 1.2275, 1.4280],
        [1.1183, 1.4738, 1.9196],
        [1.0397, 1.3150, 1.8544],
        [1.5540, 1.3618, 1.6283],
        [1.3629, 1.9835, 1.1878]], device='cuda:0')
tensor([[1.2036, 1.2275, 1.4280],
        [1.1183, 1.4738, 1.9196],
        [1.0397, 1.3150, 1.8544],
        [1.5540, 1.3618, 1.6283],
        [1.3629, 1.9835, 1.1878]], dtype=torch.float64)


In [12]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [13]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [14]:
print(y.grad_fn)

In [15]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [16]:
out.backward()

In [17]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
